### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by sgraham785** [semantic-release/git#185]
started seeing this error using `semantic-release@15` running `npx semantic-release --branch master --extends ./semantic-release/release-config.js`

```
[8:54:45 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { TypeError: Cannot read property 'name' of undefined
--
332 | at module.exports (/usr/local/lib/node_modules/@semantic-release/git/lib/prepare.js:69:38)
333 | at process._tickCallback (internal/process/next_tick.js:68:7)
334 | pluginName: '/usr/local/lib/node_modules/@semantic-release/git' }
335 | { TypeError: Cannot read property 'name' of undefined
336 | at module.exports (/usr/local/lib/node_modules/@semantic-release/git/lib/prepare.js:69:38)
337 | at process._tickCallback (internal/process/next_tick.js:68:7)
338 | pluginName: ·[32m'/usr/local/lib/node_modules/@semantic-release/git'·[39m }
339 | [Container] 2020/01/10 20:54:45 Command did not exit successfully npx semantic-release --branch master --extends ./semantic-release/release-config.js exit status 1

```

**Comment by pvdlg** [comment]
That's because you are using a version of this plugin that is meant for semantic-release 16.
There is a [`peerDependency` defined](https://github.com/semantic-release/git/blob/e38f98d7985aedc04997b7c4b6136eaea93b5fb5/package.json#L78) that should have give you a warning when you do `npm install`.

**Comment by sgraham785** [comment]
thanks. updating to semantic-release@16 fixes the issue, with no further changes for me
