### ISSUE TITLE
git tag found is incorrect tag

### ISSUE THREAD

**Issue by joelnet** [semantic-release/git#186]
I'm running this from gitlab ci/cd and having problems with a repo. The odd thing is other repos with the same .gitlab-ci.yml settings are running just fine.

semantic-release deployed a few versions successfully and then broke. semantic-release appears to be attempting write over an existing tag.

Some things about the repo:

- all tags have been created by semantic-release
- tags have not been added or removed
- there are no branches, only master
- there are some empty commits
- no rebase or rewriting of history

package.json settings:

```javascript
{
  "repository": {
    "type": "ssh",
    "url": "git@gitlabdev.paciolan.info:development/library/javascript/react/remote-components/evenue-v2-hello-world-component.git"
  },
  "release": {
    "branch": "master",
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      [
        "@semantic-release/exec",
        {
          "publishCmd": "./scripts/publish.sh ${nextRelease.version}"
        }
      ]
    ]
  }
}
```

```
$ git tag
v1.0.0
v1.0.1
v1.0.2
v1.1.0
$ git rev-list -1 v1.1.0
0f97f330745e6067dacf8908184ea8c5f2742fc0
$ echo $?
0
```

Running with the command:

```
npx semantic-release
```

Then I see this log from semantic-release:

```
[1:15:30 AM] [semantic-release] › ℹ  Found git tag v1.0.1 associated with version 1.0.1 on branch master
```

and finally this:

```
fatal: tag 'v1.1.0' already exists
```

I'm a little lost as to what to check next.

**Comment by pvdlg** [comment]
Is the tag in the history of the branch? You can verify that with `git branch --contains v1.1.0`.

**Comment by lgaticaq** [comment]
I got similar error

My semantic-release config:
```js
{
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/changelog',
    '@semantic-release/npm',
    '@semantic-release/git',
    '@semantic-release/gitlab',
    'semantic-release-gitlab-registry',
    'semantic-release-rancher'
  ]
}
```

My latest release/tag before upgrade semantic-release and plugins has **v17.13.0**.

Error log in CI:
```
$ npx semantic-release
[2:12:10 PM] [semantic-release] › ℹ  Running semantic-release version 16.0.1
[2:12:11 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[2:12:11 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[2:12:11 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[2:12:11 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[2:12:11 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "semantic-release-gitlab-registry"
[2:12:11 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "semantic-release-rancher"
[2:12:11 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[2:12:11 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[2:12:11 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[2:12:11 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[2:12:11 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[2:12:11 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[2:12:11 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[2:12:11 PM] [semantic-release] › ✔  Loaded plugin "publish" from "semantic-release-gitlab-registry"
[2:12:11 PM] [semantic-release] › ✔  Loaded plugin "publish" from "semantic-release-rancher"
[2:12:11 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[2:12:16 PM] [semantic-release] › ✔  Run automated release from branch master
[2:12:17 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[2:12:17 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[2:12:17 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[2:12:17 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[2:12:17 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[2:12:17 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[2:12:17 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[2:12:17 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
[2:12:17 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://gitlab.com/api/v4)
[2:12:17 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/gitlab"
[2:12:17 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "semantic-release-gitlab-registry"
[2:12:18 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "semantic-release-gitlab-registry"
[2:12:18 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "semantic-release-rancher"
[2:12:18 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "semantic-release-rancher"
[2:12:18 PM] [semantic-release] › ℹ  Found git tag v17.11.2 associated with version 17.11.2 on branch master
[2:12:18 PM] [semantic-release] › ℹ  Found 32 commits since last release
[2:12:18 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: xxxxxxxxxxxxxxxxxxxxxx
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[2:12:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 32 commits complete: minor release
[2:12:18 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[2:12:18 PM] [semantic-release] › ℹ  The next release version is 17.12.0
[2:12:18 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[2:12:18 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[2:12:18 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/changelog"
[2:12:18 PM] [semantic-release] [@semantic-release/changelog] › ℹ  Update /builds/xxxx/xxxx/CHANGELOG.md
[2:12:18 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/changelog"
[2:12:18 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/npm"
[2:12:18 PM] [semantic-release] [@semantic-release/npm] › ℹ  Write version 17.12.0 to package.json in /builds/xxxx/xxxx v17.12.0
[2:12:19 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/npm"
[2:12:19 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/git"
[2:12:19 PM] [semantic-release] [@semantic-release/git] › ℹ  Found 3 file(s) to commit
[2:12:21 PM] [semantic-release] [@semantic-release/git] › ℹ  Prepared Git release: v17.12.0
[2:12:21 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/git"
[2:12:22 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[2:12:22 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[2:12:22 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 128: git tag v17.12.0 xxxxxxxxxxxxxxxxxxxxxx
fatal: tag 'v17.12.0' already exists
    at makeError (/builds/xxxx/xxxx/node_modules/semantic-release/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/builds/xxxx/xxxx/node_modules/semantic-release/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async tag (/builds/xxxx/xxxx/node_modules/semantic-release/lib/git.js:217:3)
    at async run (/builds/xxxx/xxxx/node_modules/semantic-release/index.js:188:5)
    at async module.exports (/builds/xxxx/xxxx/node_modules/semantic-release/index.js:257:22)
    at async module.exports (/builds/xxxx/xxxx/node_modules/semantic-release/cli.js:55:5) {
  shortMessage: 'Command failed with exit code 128: git tag v17.12.0 xxxxxxxxxxxxxxxxxxxxxx',
  command: 'git tag v17.12.0 xxxxxxxxxxxxxxxxxxxxxx',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "fatal: tag 'v17.12.0' already exists",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Error: Command failed with exit code 128: git tag v17.12.0 xxxxxxxxxxxxxxxxxxxxxx
fatal: tag 'v17.12.0' already exists
    at makeError (/builds/xxxx/xxxx/node_modules/semantic-release/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/builds/xxxx/xxxx/node_modules/semantic-release/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async tag (/builds/xxxx/xxxx/node_modules/semantic-release/lib/git.js:217:3)
    at async run (/builds/xxxx/xxxx/node_modules/semantic-release/index.js:188:5)
    at async module.exports (/builds/xxxx/xxxx/node_modules/semantic-release/index.js:257:22)
    at async module.exports (/builds/xxxx/xxxx/node_modules/semantic-release/cli.js:55:5) {
  shortMessage: 'Command failed with exit code 128: git tag v17.12.0 xxxxxxxxxxxxxxxxxxxxxx',
  command: 'git tag v17.12.0 xxxxxxxxxxxxxxxxxxxxxx',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "fatal: tag 'v17.12.0' already exists",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
ERROR: Job failed: exit code 1
```
