### ISSUE TITLE
Cannot push tags: bad variable name

### ISSUE THREAD

**Issue by onderceylan** [semantic-release/git#187]
Hi,

For starters, thanks for all the great work on semantic-release! I hit this issue while trying to release a new version of my lib at https://github.com/onderceylan/pwa-asset-generator/runs/393609442#step:9:456 

This never happened before so I have no idea what's wrong there. When I run it with dry-mode on my client machine, I get "Skip v2.2.0 tag creation in dry-run mode" which tells it's a usual tag. I've no idea about git's "bad variable name" error. 

Can you please help?

```
[5:02:07 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: git push --tags https://[secure]@github.com/onderceylan/pwa-asset-generator.git HEAD:master
    at makeError (/home/runner/work/pwa-asset-generator/pwa-asset-generator/node_modules/@semantic-release/git/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/home/runner/work/pwa-asset-generator/pwa-asset-generator/node_modules/@semantic-release/git/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async push (/home/runner/work/pwa-asset-generator/pwa-asset-generator/node_modules/@semantic-release/git/lib/git.js:54:3)
    at async module.exports (/home/runner/work/pwa-asset-generator/pwa-asset-generator/node_modules/@semantic-release/git/lib/prepare.js:48:5)
    at async prepare (/home/runner/work/pwa-asset-generator/pwa-asset-generator/node_modules/@semantic-release/git/index.js:28:3)
    at async validator (/home/runner/work/pwa-asset-generator/pwa-asset-generator/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/runner/work/pwa-asset-generator/pwa-asset-generator/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /home/runner/work/pwa-asset-generator/pwa-asset-generator/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async Object.pluginsConf.<computed> [as prepare] (/home/runner/work/pwa-asset-generator/pwa-asset-generator/node_modules/semantic-release/lib/plugins/index.js:80:11) {
  command: 'git push --tags https://[secure]@github.com/onderceylan/pwa-asset-generator.git HEAD:master',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '.git/hooks/pre-push: 70: export: refs/heads/master: bad variable name\n' +
    "error: failed to push some refs to 'https://[secure]@github.com/onderceylan/pwa-asset-generator.git'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: '@semantic-release/git'
}
```

**Comment by onderceylan** [comment]
Sorry for the noise. Apparently this is related to husky's pre-push hook. Not at all related to semantic-release.
