### ISSUE TITLE
Prepare step error

### ISSUE THREAD

**Issue by yyynnn** [semantic-release/git#204]
Hi!
While in Gitlab CI I get this:
[5:31:36 PM] [semantic-release] [@semantic-release/git] › ℹ  Found 2 file(s) to commit
 [5:31:45 PM] [semantic-release] › ✖  Failed step "prepare" of plugin "@semantic-release/git"
 [5:31:45 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1:
....
 pre-commit: 
 pre-commit: We've failed to pass the specified git pre-commit hooks as the `test`
 pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
 pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
 pre-commit: 
 pre-commit:   git commit -n (or --no-verify)
 pre-commit: 
 pre-commit: This is ill-advised since the commit is broken.
 pre-commit: 
     at makeError (/builds/fmaas/application/frontend_bfp/node_modules/@semantic-release/git/node_modules/execa/lib/error.js:58:11)
     at handlePromise (/builds/fmaas/application/frontend_bfp/node_modules/@semantic-release/git/node_modules/execa/index.js:114:26)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
     at async commit (/builds/fmaas/application/frontend_bfp/node_modules/@semantic-release/git/lib/git.js:38:3)
     at async module.exports (/builds/fmaas/application/frontend_bfp/node_modules/@semantic-release/git/lib/prepare.js:63:5)
     at async prepare (/builds/fmaas/application/frontend_bfp/node_modules/@semantic-release/git/index.js:28:3)
     at async validator (/builds/fmaas/application/frontend_bfp/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
     at async /builds/fmaas/application/frontend_bfp/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
     at async /builds/fmaas/application/frontend_bfp/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
     at async Object.pluginsConf.<computed> [as prepare] (/builds/fmaas/application/frontend_bfp/node_modules/semantic-release/lib/plugins/index.js:80:11) {
.....

While releasing locally I get clean run without errors

**Comment by yyynnn** [comment]
cache error

**Comment by maksym-leichenko** [comment]
I have same error.

> cache error
What is it mean?
