### ISSUE TITLE
Settings assets to false results in error

### ISSUE THREAD

**Issue by bestickley** [semantic-release/git#280]
With this .releaserc.js:
```js
module.exports = {
  branches: ["main"],
  plugins: [
    "@semantic-release/commit-analyzer", // analyzes commits with conventional-changelog standrd
    "@semantic-release/release-notes-generator", // generates changelog content based on conventional-changelog standard
    "@semantic-release/changelog", // updates CHANGELOG.md
    "@semantic-release/npm", // updates version in package.json based on commits
    ["@semantic-release/git", { assets: false }],
  ],
};
```
I get this error: 
```
[3:43:47 PM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: assets.map is not a function
--
130 | at module.exports (/codebuild/output/src038058146/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/gb-static-site/node_modules/@semantic-release/git/lib/prepare.js:37:14)
131 | at processTicksAndRejections (internal/process/task_queues.js:93:5)
132 | at async prepare (/codebuild/output/src038058146/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/gb-static-site/node_modules/@semantic-release/git/index.js:28:3)
133 | at async validator (/codebuild/output/src038058146/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/gb-static-site/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
134 | at async /codebuild/output/src038058146/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/gb-static-site/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
135 | at async /codebuild/output/src038058146/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/gb-static-site/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
136 | at async Object.pluginsConf.<computed> [as prepare] (/codebuild/output/src038058146/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/gb-static-site/node_modules/semantic-release/lib/plugins/index.js:80:11)
137 | at async run (/codebuild/output/src038058146/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/gb-static-site/node_modules/semantic-release/index.js:185:3)
138 | at async module.exports (/codebuild/output/src038058146/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/gb-static-site/node_modules/semantic-release/index.js:260:22)
139 | at async module.exports (/codebuild/output/src038058146/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/gb-static-site/node_modules/semantic-release/cli.js:55:5) {
140 | pluginName: '@semantic-release/git'
141 | }
142 | TypeError: assets.map is not a function
143 | at module.exports (/codebuild/output/src038058146/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/gb-static-site/node_modules/@semantic-release/git/lib/prepare.js:37:14)
144 | at processTicksAndRejections (internal/process/task_queues.js:93:5)
145 | at async prepare (/codebuild/output/src038058146/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/gb-static-site/node_modules/@semantic-release/git/index.js:28:3)
146 | at async validator (/codebuild/output/src038058146/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/gb-static-site/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
147 | at async /codebuild/output/src038058146/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/gb-static-site/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
148 | at async /codebuild/output/src038058146/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/gb-static-site/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
149 | at async Object.pluginsConf.<computed> [as prepare] (/codebuild/output/src038058146/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/gb-static-site/node_modules/semantic-release/lib/plugins/index.js:80:11)
150 | at async run (/codebuild/output/src038058146/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/gb-static-site/node_modules/semantic-release/index.js:185:3)
151 | at async module.exports (/codebuild/output/src038058146/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/gb-static-site/node_modules/semantic-release/index.js:260:22)
152 | at async module.exports (/codebuild/output/src038058146/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/gb-static-site/node_modules/semantic-release/cli.js:55:5) {
153 | pluginName: '@semantic-release/git'
154 | }
```

Is the documentation wrong? Docs say I should be able to set assets to false.

**Comment by liemdo** [comment]
I get the same error as well.

**Comment by micalevisk** [comment]
The issue is that here:

https://github.com/semantic-release/git/blob/09e00f98205e81e17ad9ec056a1efe20b42efb2a/lib/prepare.js#L37

isn't expected that `assets` could be `false`, as allowed here:

https://github.com/semantic-release/git/blob/7756d6411d93228e77e56e6fb07944e04d343a58/lib/resolve-config.js#L6-L8
