### ISSUE TITLE
Error while releasing it through semantic release github.

### ISSUE THREAD

**Issue by ravali-rimmalapudi** [semantic-release/git#298]
I am running semantic release to do a github release. This is the configuration:
```
semantic-release: 18.0.0
"@semantic-release/changelog": "^5.0.1",
"@semantic-release/exec": "^5.0.0",
"@semantic-release/git": "^9.0.0",
``` 
Getting the following error:
```
An error occurred while running semantic-release: RequestError [HttpError]: Validation Failed: {"resource":"Search","field":"q","code":"missing"}
    at /home/runner/.npm/_npx/1624/lib/node_modules/semantic-release/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  status: 422,
  response: {
    url: 'https://api.github.com/search/issues?q=repo%3Aravali-rimmalapudi%2Ftwilio-cli-core+type%3Apr+is%3Amerged+3b0208ab2e23458110e433ce8dd06ddcf4d7be25+9e519adc2e8fa3dc79ebb64b318d89922bf5c4bb+54b385671fd5f6829fedb57e165e7bd98ba9b641+716e0a1f1211ee5c8ad21bee6b3e9def31243eb5',
    status: 422,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
      'cache-control': 'no-cache',
      connection: 'close',
      'content-length': '149',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Tue, 21 Sep 2021 07:04:05 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept, Authorization, Cookie, X-GitHub-OTP, Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '07C0:89DF:165048:1A368B:614983E5',
      'x-ratelimit-limit': '30',
      'x-ratelimit-remaining': '17',
      'x-ratelimit-reset': '1632207879',
      'x-ratelimit-resource': 'search',
      'x-ratelimit-used': '13',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Validation Failed',
      errors: [Array],
      documentation_url: 'https://docs.github.com/v3/search'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/search/issues?q=repo%3Aravali-rimmalapudi%2Ftwilio-cli-core+type%3Apr+is%3Amerged+3b0208ab2e23458110e433ce8dd06ddcf4d7be25+9e519adc2e8fa3dc79ebb64b318d89922bf5c4bb+54b385671fd5f6829fedb57e165e7bd98ba9b641+716e0a1f1211ee5c8ad21bee6b3e9def31243eb5',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.10.0 octokit-core.js/3.5.1 Node.js/14.17.6 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { agent: undefined, hook: [Function: bound bound register] }
  },
  attemptNumber: 4,
  retriesLeft: 0,
  pluginName: '@semantic-release/github'
}
AggregateError: 
    HttpError: Validation Failed: {"resource":"Search","field":"q","code":"missing"}
        at /home/runner/.npm/_npx/1624/lib/node_modules/semantic-release/node_modules/@octokit/request/dist-node/index.js:86:21
    at /home/runner/.npm/_npx/1624/lib/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.pluginsConf.<computed> [as success] (/home/runner/.npm/_npx/1624/lib/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/home/runner/.npm/_npx/1624/lib/node_modules/semantic-release/index.js:201:3)
    at async module.exports (/home/runner/.npm/_npx/1624/lib/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/home/runner/.npm/_npx/1624/lib/node_modules/semantic-release/cli.js:55:5)
```

**Comment by travi** [comment]
resolved by https://github.com/semantic-release/github/issues/415#issuecomment-924454086

**Comment by nomankt** [comment]
+1
