### ISSUE TITLE
Assets try to push on GitHub instead of GitLab

### ISSUE THREAD

**Issue by kopax** [semantic-release/git#49]
# Expected

I expect to publish on gitlab

# Result

I publish on GitHub

# Reproduction

```yml
{
"devDependencies": {
    "@semantic-release/git": "^5.0.0",
    "@semantic-release/gitlab": "^2.1.4",
    "@semantic-release/npm": "^3.2.5"
},
"release": {
    "branch": "master",
    "npmPublish": false,
    "verifyConditions": [
      "@semantic-release/npm",
      "@semantic-release/git",
      {
        "path": "@semantic-release/gitlab",
        "gitlabUrl": "https://gitlab.example.com"
      }
    ],
    "prepare": [
      "@semantic-release/npm",
      {
        "path": "@semantic-release/git",
        "assets": [
          {
            "path": "package.json"
          },
          {
            "path": "dist/*.es.js",
            "label": "1 file ES6"
          },
          {
            "path": "dist/*.es.js.map",
            "label": "1 file ES6 sourcemap"
          },
          {
            "path": "dist/*.min.js",
            "label": "1 file UMD compressed"
          },
          {
            "path": "dist/*.min.js.map",
            "label": "1 file UMD compressed sourcemap"
          },
          {
            "path": "dist/*.js",
            "label": "1 file UMD uncompressed"
          },
          {
            "path": "dist/*.js.map",
            "label": "1 file UMD uncompressed sourcemap"
          },
          {
            "path": "lib/*.js",
            "label": "source files ES5"
          }
        ],
        "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      }
    ],
    "publish": [
      "@semantic-release/npm",
      {
        "path": "@semantic-release/gitlab",
        "gitlabUrl": "https://gitlab.example.com"
      }
    ]
  }
}
```

Logs

```ruby
$ npx semantic-release
npx: installed 377 in 11.097s
[Semantic release]: Running semantic-release version 15.4.1
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/git
[Semantic release]: Load plugin verifyConditions from @semantic-release/gitlab
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/npm
[Semantic release]: Load plugin prepare from @semantic-release/git
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/gitlab
[Semantic release]: Load plugin success from @semantic-release/github
[Semantic release]: Load plugin fail from @semantic-release/github
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify GitLab authentication (https://git.example.com/api/v4)
[Semantic release]: Found git tag v0.3.4 associated with version 0.3.4
[Semantic release]: Found 4 commits since last release
[Semantic release]: Call plugin analyze-commits
[Semantic release]: Analyzing commit: Merge branch 'dev' into 'master'

fix(release): installing plugins

See merge request dev-tools/rollup-umd-scripts!75
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: fix(release): installing plugins
[Semantic release]: The release type for the commit is patch
[Semantic release]: Analyzing commit: fix(release): installing plugins
[Semantic release]: The release type for the commit is patch
[Semantic release]: Analyzing commit: Merge branch 'dev' into 'master'

fix(release): installing plugins

See merge request dev-tools/rollup-umd-scripts!74
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analysis of 4 commits complete: patch release
[Semantic release]: The next release version is 0.3.5
[Semantic release]: Call plugin verify-release
[Semantic release]: Call plugin generateNotes
[Semantic release]: Call plugin prepare
[Semantic release]: Wrote version 0.3.5 to package.json
[Semantic release]: Wrote version 0.3.5 to package-lock.json
[Semantic release]: Found 1 file(s) to commit
[Semantic release]: Creating tag v0.3.5
[Semantic release]: Prepared Git release: v0.3.5
[Semantic release]: Call plugin generateNotes
[Semantic release]: Create tag v0.3.5
[Semantic release]: Call plugin publish
[Semantic release]: Published GitLab release: v0.3.5
[Semantic release]: Verify GitHub authentication
[Semantic release]: Verify GitHub authentication
[Semantic release]: ENOGHTOKEN No GitHub token specified.
A GitHub personnal token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.

Please make sure to create a GitHub personnal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) and to set it in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment. The token must allow to push to the repository dev-tools/rollup-umd-scripts.


[Semantic release]: ENOGHTOKEN No GitHub token specified.
A GitHub personnal token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.

Please make sure to create a GitHub personnal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) and to set it in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment. The token must allow to push to the repository dev-tools/rollup-umd-scripts.


{ SemanticReleaseError: No GitHub token specified.
    at module.exports (/root/.npm/_npx/56/lib/node_modules/semantic-release/node_modules/@semantic-release/github/lib/get-error.js:6:10)
    at module.exports (/root/.npm/_npx/56/lib/node_modules/semantic-release/node_modules/@semantic-release/github/lib/verify.js:98:17)
    at success (/root/.npm/_npx/56/lib/node_modules/semantic-release/node_modules/@semantic-release/github/index.js:38:11)
    at validator (/root/.npm/_npx/56/lib/node_modules/semantic-release/lib/plugins/normalize.js:43:28)
    at pReduce (/root/.npm/_npx/56/lib/node_modules/semantic-release/lib/plugins/pipeline.js:36:40)
    at Promise.all.then.value (/root/.npm/_npx/56/lib/node_modules/semantic-release/node_modules/p-reduce/index.js:16:10)
    at process._tickCallback (internal/process/next_tick.js:178:7)
  name: 'SemanticReleaseError',
  code: 'ENOGHTOKEN',
  details: 'A [GitHub personnal token](https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the `GH_TOKEN` or `GITHUB_TOKEN` environment variable on your CI environment.\n\nPlease make sure to create a [GitHub personnal token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) and to set it in the `GH_TOKEN` or `GITHUB_TOKEN` environment variable on your CI environment. The token must allow to push to the repository dev-tools/rollup-umd-scripts.',
  semanticRelease: true,
  pluginName: '@semantic-release/github' }
ERROR: Job failed: exit code 1

```

**Comment by kopax** [comment]
I have no more issue if I do : 

```bash
$ npm install --save-dev @semantic-release/gitlab-config
```

and do in `package.json`

```diff
{
  "release": {
+    "extends": "@semantic-release/gitlab-config",
  }
}
```

But this is not marked as a requirement for `@semantic-release/gitlab` to work. Can I get some clarification on that point?

**Comment by pvdlg** [comment]
As indicated in the logs:
```
[Semantic release]: Load plugin success from @semantic-release/github
[Semantic release]: Load plugin fail from @semantic-release/github
```

You are using the github plugin for the `fail` and `success` hooks. This is because they are the default ones. If you want to disable them you should set `success` and `fail` to `false`.
This is not super intuitive, this is why we provide shareable config such as `@semantic-release/gitlab-config` that does that for you.

**Comment by kopax** [comment]
@pvdlg I have read `@semantic-release/gitlab-config` and took the exact same configuration but it wasn't working better.

The problem for came from : 

- I was not installing `gitlab-config` but `gitlab` plugin can't work without it, It wasn't successful  operation to do the exact same config and not having it.
- git plugin can't work with gitlab and if installed it will try to push on github.

I am not sure if the 2nd point is correct but the 1st one, I couldn't do it without it.

**Comment by pvdlg** [comment]
`@semantic-release/gitlab` is the actual plugin to publish to GitLab. `@semantic-release/gitlab-config` is a shareable configuration that defines a semantic-release config to publish to GitLab. The config in `@semantic-release/gitlab-config` uses `@semantic-release/gitlab`.

> I was not installing gitlab-config but gitlab plugin can't work without it

That is not correct. `@semantic-release/gitlab` can absolutely works `@semantic-release/gitlab-config`. As explain before semantic-release uses the `@semantic-release/github` plugin by default for several steps (`verifyConditions`, `publish`, `success` and `fail`). If you don't override the config for each of these steps then the `@semantic-release/github` is used. This is what happened in the logs you provided before.

> It wasn't successful operation to do the exact same config and not having it.

That is not correct. `@semantic-release/gitlab-config` is a shareable config, the only things it does is to define a semantic-release configuration as a JSON object. Copying/pasting the content of `@semantic-release/gitlab-config` into your semantic-release config is exactly the same thing as doing `"extends": "@semantic-release/gitlab-config"`.

> git plugin can't work with gitlab and if installed it will try to push on github.

That is not correct. The `@semantic-release/git` plugin can be used with Git repository/host.
Once again, as mentioned before, it wasn't the `@semantic-release/git` plugin that was trying to access GitHub, it was the `@semantic-release/github` plugin used in the `fail` step, which is the default when the `fail` step is not overwritten in your config.

**Comment by kopax** [comment]
@pvdlg, I have done testing and arrived with a different conclusion.
You should now that I was testing and expecting exactly what you have just wrote. I ended up with a different conclusion.

I recognize totally that it doesn't make sense. I choose to use both because of that. I can try to do more test, or I can try to remove the config plugin from a repo to show you that it won't work.

Regarding ` @semantic-release/git` plugin, I can also do a commit that will install it and you will notice that it will try to push to github.

Do you want me to proceed (1 by 1)?

**Comment by pvdlg** [comment]
Yes please.

**Comment by kopax** [comment]
> Copying/pasting the content of `@semantic-release/gitlab-config/index.js` into your semantic-release config is exactly the same thing as doing `"extends": "@semantic-release/gitlab-config"`.

So I have reproduced the test env and I feel ashamed that it was finally only disturbance for you.

All your point were proved. I know I was trying to get my config work without `@semantic-release/gitlab-config`, but I was not able to run the test before. I wont search the CI as they are many since.

But still, thanks you for supporting your users, and for releasing such a good tool.
