### ISSUE TITLE
any particular reason for not having `publish` plugin?

### ISSUE THREAD

**Issue by grubyak** [semantic-release/git#63]
please correct me if i am mistaken - i assume that `@semantic-release/github` is for public github (github.com), while `@semantic-release/git` for private github instances (non github.com)

while publishing to a private git server works, there are some errors:
```
...
[Semantic release]: Call plugin generateNotes
  semantic-release:release-notes-generator version: '1.3.3' +4s
  semantic-release:release-notes-generator host: 'git.myserver.com' +0ms
  semantic-release:release-notes-generator owner: 'joe' +0ms
  semantic-release:release-notes-generator repository: 'repo' +0ms
  semantic-release:release-notes-generator previousTag: 'v1.3.2' +0ms
  semantic-release:release-notes-generator currentTag: 'v1.3.3' +0ms
Semantic release]: Create tag v1.3.3
[Semantic release]: Call plugin publish
[Semantic release]: Verify GitHub authentication (https://git.myserver.com/joe/repo)
[Semantic release]: An error occurred while running semantic-release: { HttpError:
    at response.text.then.message (/Users/joe/.nvm/versions/node/v10.1.0/lib/node_modules/semantic-release/node_modules/@octokit/rest/lib/request/request.js:78:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HttpError',
  code: 406,
  status: undefined,
  headers:
   { 'cache-control': 'no-cache, no-store',
     connection: 'close',
     'content-security-policy': 'default-src \'none\'; base-uri \'self\'; block-all-mixed-content; child-src \'self\'; connect-src \'self\' git.myserver.com status.github.com wss://git.myserver.com; font-src \'self\'; form-action \'self\' git.myserver.com; frame-ancestors \'none\'; img-src * data:; manifest-src \'self\'; media-src \'none\'; script-src \'self\'; style-src \'unsafe-inline\' \'self\'; worker-src \'self\'',
     'content-type': 'text/html; charset=utf-8',
     date: 'Tue, 17 Jul 2018 09:05:57 GMT',
     server: 'GitHub.com',
     'set-cookie': '...; path=/; secure; HttpOnly',
     status: '406 Not Acceptable',
     'strict-transport-security': 'max-age=31536000; includeSubdomains',
     'transfer-encoding': 'chunked',
     vary: 'X-PJAX',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'deny',
     'x-github-request-id': '380ec586-1234-1234-1234-5a544de60b9c',
     'x-request-id': '...',
     'x-runtime': '0.005339',
     'x-runtime-rack': '0.009056',
     'x-ua-compatible': 'IE=Edge,chrome=1',
     'x-xss-protection': '1; mode=block' },
  pluginName: '@semantic-release/github' }
...
```

looks like `githubUrl` is not respected as in attached error i can see `server: 'GitHub.com',` - after that a new release is present in the repo, but still i want to get rid off that error message, any hints?

**Comment by grubyak** [comment]
i got it working... you can close the ticket ;)

```
{
    ...
    "verifyConditions": [
        "@semantic-release/changelog",
        {
            "path": "@semantic-release/github",
            "githubUrl": "https://git.myserver.com",
            "githubApiPathPrefix": "/api/v3"
        }
    ],
    "publish": [
        {
            "path": "@semantic-release/github",
            "githubUrl": "https://git.myserver.com",
            "githubApiPathPrefix": "/api/v3",
            "assets": [
                "package.json",
                ...
            ]
        }
    ],
    ...
}
```
