### ISSUE TITLE
semantic-release v15.8.0 + @semantic-release/git v7.0.0 does not work

### ISSUE THREAD

**Issue by grubyak** [semantic-release/git#64]
for me it still does not work as `cwd` is undefined and it causes following error:

```
[Semantic release]: An error occurred while running semantic-release: { TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1090:7)
    at module.exports (/Users/joe/code/test/node_modules/@semantic-release/git/lib/prepare.js:42:30)
    at process._tickCallback (internal/process/next_tick.js:68:7) pluginName: '@semantic-release/git' }
```

**Comment by pvdlg** [comment]
Can you provide a link to your repo or to the build?

**Comment by joshdcomp** [comment]
Having the same issue—the offending line seems to be `const changelogPath = path.resolve(cwd, CHANGELOG);`, not sure if it's just expecting the changelog to be included in the assets or something else. 

Can't speak for @grubyak but my `.releaserc` file is:

```json
{
    "branch": "master",
    "repository": "https://git.nmlv.nml.com/fx-uitk/ui-toolkit",
    "verifyConditions": [],
    "prepare": [
      "@semantic-release/npm",
      {
        "path": "@semantic-release/git",
        "assets": ["package.json", "package-lock.json"],
        "message": "chore(release): Release ${nextRelease.version} - ${new Date().toLocaleDateString('en-US', {year: 'numeric', month: 'short', day: 'numeric', hour: 'numeric', minute: 'numeric' })} [skip ci]\n\n${nextRelease.notes}"
      }
    ],
    "publish": [
      "@semantic-release/npm",
      "@semantic-release/gitlab"
    ],
    "success": false,
    "fail": false,
    "debug": true
}
```

Relevant logs:

```bash 
See merge request fx-uitk/ui-toolkit!1
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: updated form label default color for nm-px theme
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analysis of 155 commits complete: minor release
[Semantic release]: The next release version is 2.1.0
[Semantic release]: Call plugin "generateNotes"
[Semantic release]: Call plugin "prepare"
[Semantic release]: Verify authentication for registry https://sinopia.nmlv.nml.com/
[Semantic release]: Wrote version 2.1.0 to package.json
[Semantic release]: Wrote version 2.1.0 to package-lock.json
[Semantic release]: Call plugin "prepare"
[Semantic release]: An error occurred while running semantic-release: { TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1181:7)
    at module.exports (/builds/fx-uitk/ui-toolkit/node_modules/@semantic-release/git/lib/prepare.js:41:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) pluginName: '@semantic-release/git' }
{ TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1181:7)
    at module.exports (/builds/fx-uitk/ui-toolkit/node_modules/@semantic-release/git/lib/prepare.js:41:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) pluginName: '@semantic-release/git' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @uitk/ui-toolkit-testing@2.0.0 next_release:publish: `npx semantic-release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @uitk/ui-toolkit-testing@2.0.0 next_release:publish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-17T21_39_06_626Z-debug.log
ERROR: Job failed: exit code 1
```

**Comment by pvdlg** [comment]
What version or semantic-release are you using? What’s the first line of logs?

**Comment by joshdcomp** [comment]
Turns out I was running `15.7.2` for the above output, here's the first line of that log:

```$ npm run next_release:publish

> @uitk/ui-toolkit-testing@2.0.0 next_release:publish /builds/fx-uitk/ui-toolkit
> npx semantic-release

[Semantic release]: Running semantic-release version 15.7.2
[Semantic release]: Load plugin "analyzeCommits" from @semantic-release/commit-analyzer
[Semantic release]: Load plugin "generateNotes" from @semantic-release/release-notes-generator
[Semantic release]: Load plugin "prepare" from @semantic-release/npm
[Semantic release]: Load plugin "prepare" from @semantic-release/git
[Semantic release]: Load plugin "publish" from @semantic-release/npm
[Semantic release]: Load plugin "publish" from @semantic-release/gitlab
[Semantic release]: Run automated release from branch master```

**Comment by joshdcomp** [comment]
When I update to `15.8.0` I get a different error (it should be noted I used the example release message from the docs):

```
$ npm run next_release:publish

> @uitk/ui-toolkit-testing@2.0.0 next_release:publish /builds/fx-uitk/ui-toolkit
> npx semantic-release

[Semantic release]: Running semantic-release version 15.8.0
[Semantic release]: Load plugin "analyzeCommits" from @semantic-release/commit-analyzer
[Semantic release]: Load plugin "generateNotes" from @semantic-release/release-notes-generator
[Semantic release]: Load plugin "prepare" from @semantic-release/npm
[Semantic release]: Load plugin "prepare" from @semantic-release/git
[Semantic release]: Load plugin "publish" from @semantic-release/npm
[Semantic release]: Load plugin "publish" from @semantic-release/gitlab
[Semantic release]: Run automated release from branch master

...

[Semantic release]: Call plugin "prepare"
[Semantic release]: Found 2 file(s) to commit
[Semantic release]: An error occurred while running semantic-release: { SyntaxError: Unexpected token )
    at Function (<anonymous>)
    at /builds/fx-uitk/ui-toolkit/node_modules/lodash/lodash.js:14843:16
    at apply (/builds/fx-uitk/ui-toolkit/node_modules/lodash/lodash.js:494:27)
    at /builds/fx-uitk/ui-toolkit/node_modules/lodash/lodash.js:15227:16
    at apply (/builds/fx-uitk/ui-toolkit/node_modules/lodash/lodash.js:496:27)
    at /builds/fx-uitk/ui-toolkit/node_modules/lodash/lodash.js:6600:16
    at template (/builds/fx-uitk/ui-toolkit/node_modules/lodash/lodash.js:14842:20)
    at module.exports (/builds/fx-uitk/ui-toolkit/node_modules/@semantic-release/git/lib/prepare.js:96:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  source: 'function(obj) {\nobj || (obj = {});\nvar __t, __p = \'\';\nwith (obj) {\n__p += \'chore(release): Release \' +\n((__t = (nextRelease.version)) == null ? \'\' : __t) +\n\' - \' +\n((__t = (new Date().toLocaleDateString(\'en-US\', {year: \'numeric\', month: \'short\', day: \'numeric\', hour: \'numeric\', minute: \'numeric\' )) == null ? \'\' : __t) +\n\')} [skip ci]\\n\\n\' +\n((__t = (nextRelease.notes)) == null ? \'\' : __t);\n\n}\nreturn __p\n}',
  pluginName: '@semantic-release/git' }
{ SyntaxError: Unexpected token )
    at Function (<anonymous>)
    at /builds/fx-uitk/ui-toolkit/node_modules/lodash/lodash.js:14843:16
    at apply (/builds/fx-uitk/ui-toolkit/node_modules/lodash/lodash.js:494:27)
    at /builds/fx-uitk/ui-toolkit/node_modules/lodash/lodash.js:15227:16
    at apply (/builds/fx-uitk/ui-toolkit/node_modules/lodash/lodash.js:496:27)
    at /builds/fx-uitk/ui-toolkit/node_modules/lodash/lodash.js:6600:16
    at template (/builds/fx-uitk/ui-toolkit/node_modules/lodash/lodash.js:14842:20)
    at module.exports (/builds/fx-uitk/ui-toolkit/node_modules/@semantic-release/git/lib/prepare.js:96:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  source: 'function(obj) {\nobj || (obj = {});\nvar __t, __p = \'\';\nwith (obj) {\n__p += \'chore(release): Release \' +\n((__t = (nextRelease.version)) == null ? \'\' : __t) +\n\' - \' +\n((__t = (new Date().toLocaleDateString(\'en-US\', {year: \'numeric\', month: \'short\', day: \'numeric\', hour: \'numeric\', minute: \'numeric\' )) == null ? \'\' : __t) +\n\')} [skip ci]\\n\\n\' +\n((__t = (nextRelease.notes)) == null ? \'\' : __t);\n\n}\nreturn __p\n}',
  pluginName: '@semantic-release/git' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @uitk/ui-toolkit-testing@2.0.0 next_release:publish: `npx semantic-release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @uitk/ui-toolkit-testing@2.0.0 next_release:publish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-18T02_37_14_918Z-debug.log
ERROR: Job failed: exit code 1
```

**Comment by pvdlg** [comment]
As indicated in the [release note](https://github.com/semantic-release/git/releases/tag/v7.0.0) the version `7.0.0` of this plugin is only compatible with semantic-release 15.8.0.

The error you have is due to your `message` option being an invalid lodash template because you have `{` and `}` inside each other.

Use that instead: `"chore(release): Release ${nextRelease.version} - <%=new Date().toLocaleDateString('en-US', {year: 'numeric', month: 'short', day: 'numeric', hour: 'numeric', minute: 'numeric' })%> [skip ci]\n\n${nextRelease.notes}"`

**Comment by joshdcomp** [comment]
@pvdlg I'll give that a shot, but I would request the docs be updated, as the `message` I was using was a direct copy/paste from the Readme

**Comment by grubyak** [comment]
@pvdlg while filing the ticket i was on semantic-release v15.8.0 + @semantic-release/git v7.0.0 (verified my package.json from that day), today however i cannot reproduce it anymore :S

**Comment by pvdlg** [comment]
I guess you were using the wrong version due to a `package-lock.json` or `yarn.lock` file.
